#!/bin/bash

########################################
############# CSCI 2951-O ##############
########################################

# Used to remove .class files generated by the compile script
find src -type f -name "*.class" -delete